"""add mitre_tactics to anomalies

Revision ID: c1a2b3d4e5f6
Revises: b32bfd4fba3b
Create Date: 2026-04-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a2b3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'b32bfd4fba3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'anomalies',
        sa.Column('mitre_tactics', postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False, server_default='[]')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomalies', 'mitre_tactics')
    # ### end Alembic commands ###
